### PR TITLE
Move code from archived sdk-dotnet repo

### PR DESCRIPTION
**Pull request by ryjones**
This is a copy of the code in

github.com/hyperledger-archives/sawtooth-sdk-dotnet

at commit

fa44caa20b1551b528850b43225c122ef6012e4c

### CODE REVIEW

**Comment by vaporos** [comment]
From a process perspective, we want to keep the entire history. Something like a) create branch from previous repo; b) purge anything that won't be copied over; c) move everything to a subdirectory;d) merge that into sawtooth-contrib and create PR

**Comment by ryjones** [comment]
Sure. I see the marketplace code has been in a pending PR since 08 JAN 2020.

**Comment by vaporos** [comment]
> Sure. I see the marketplace code has been in a pending PR since 08 JAN 2020.

Yeah, Richard was working on this in the background before he got busy. Just lost track of it. Probably just needs review.

**Comment by ryjones** [comment]
@vaporos it's been quite a while - chance to clean this up?

**Pull request closed without merging**
